### ISSUE TITLE
Integrate back swagger-codegen when it supports webflux

### ISSUE THREAD

**Issue by fischermatte** [fischermatte/geolud#45]
see 

- https://github.com/swagger-api/swagger-codegen/issues/7217
- https://github.com/springfox/springfox/issues/1773
- https://github.com/springfox/springfox/issues/2416

**Comment by cbornet** [comment]
You should have a look at https://github.com/OpenAPITools/openapi-generator

**Comment by fischermatte** [comment]
wont swagger in near future
