### ISSUE TITLE
rewrite backend using nodejs

### ISSUE THREAD

**Issue by fischermatte** [fischermatte/geolud#70]
since pricing in java is :(

**Comment by justudin** [comment]
Hi @fischermatte! Could you please elaborate the detail?
I have the implementation of backend restfull api which utilizes nodejs+expressjs+mongodb+mongoose. 
I think it can be used as a basic starting point: https://github.com/justudin/projectrestapi

Love to hear your idea.
Thanks!

**Comment by fischermatte** [comment]
thx @justudin. looks good. i decided to use NestJS with TypeORM for this purpose.
