### ISSUE TITLE
Client branch without GraphQL

### ISSUE THREAD

**Issue by ronyitc** [fischermatte/geolud#90]
Hi @fischermatte Thanks a lot for such awesome well maintained cutting edge blog project. I would like to play with your code for my personal learning. Can you please give me the commit hash or branch where I get the  client without GraphQL working with Java Backend.

**Comment by fischermatte** [comment]
thx for feedback. i have currently limited internet access. i think it is tag 1.5.2. will have a look later.

**Comment by fischermatte** [comment]
ok, just tested it. it is 1.5.2. still on java 8. there is somehow an issue at least on localhost with the websocket connection (for chat) which i couldn't figure out.
